import "@/assets/styles/one.css";
import "@/assets/styles/two.css";
import "@/assets/styles/three.css";
import "@/assets/styles/four.css";
import "@/assets/styles/five.css";
import Navbar from "@/components/Navbar";


export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://lexend-nextjs.vercel.app/_next/static/css/efdc06e3a295b1d3.css"
        />
      </head>
      <body className="font-bodyfont text-cfont">
        {" "}
        <Navbar /> {children}
      </body>
    </html>
  );
}
